heat_template_version: 2015-04-30
parameters:
  network_name:
    type: string
    label: network name
resources:
  NF1_Infra:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: OS::Nova::Server
        properties:
          name: nf1vm_%index%
          flavor: m1.tiny
          image: cirros
          networks:
            - network: { get_param: network_name }
          key_name: mykey
          security_groups:
            - default
  NF2_Infra:
    type: OS::Heat::ResourceGroup
    properties:
      count: 2
      resource_def:
        type: OS::Nova::Server
        properties:
          name: nf2vm%index%
          flavor: m1.tiny
          image: cirros
          networks:
            - network: { get_param: network_name }
          key_name: mykey
          security_groups:
            - default
